version: "3.8"
services:
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    restart: always
    image: clean_ts_api
    command: npm start
    volumes:
      - ./dist:/usr/src/clean_ts_api/dist
    ports:
      - "5050:5050"
    links:
      - mongo
